### ISSUE TITLE
meta-bind edits unrelated YAML

### ISSUE THREAD

**Issue by Amir1453** [mProjectsCode/obsidian-meta-bind-plugin#92]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
When meta-bind input field exists, it changes all undeclared YAML metadate to `null`

**To Reproduce**

1. Create new file
2. Add YAML fields cat and dog
4. Create meta-bind field for cat
5. Use the meta-bind field (e.g. enter a number)
6. dog will get updated to null

**Expected behavior**
dog field is unaffected

**Screenshots**
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/63464110/524031d7-a969-44e2-9c2b-a53044eb82af)
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/63464110/cbf657d7-ece1-4301-b56a-417a6676934c)
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/63464110/58a9c099-c408-4ea1-8c63-6d9fba3923b0)
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/63464110/43716ec3-43df-4942-8d12-c447c02d0702)

**Occurs on**

-   [ ] Windows
-   [ ] macOS
-   [x] Linux (Fedora 37 Kernel: 6.3.6-100.fc37.x86_64)
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.4.3

**Additional context**
Obsidian is sandboxed via `firejail`.

**Comment by mProjectsCode** [comment]
That is caused by Obsidians metadata API. There is nothing I can do about it.
